### ISSUE TITLE
Missing /kythe/edge/param for /kythe/edge/ref/call function

### ISSUE THREAD

**Issue by BFergerson** [google/kythe#2922] opened 2018-08-11 22:08 UTC
This is a follow up from: https://groups.google.com/forum/#!topic/kythe/I2vpv8L9oV0
I'm using Kythe 0.28

The instructions to produce the triples file which is missing the **/kythe/edge/param** should be:
```
git clone https://github.com/bfergerson/otherproject
cd otherproject

export REAL_JAVAC="$(which javac)"
export JAVAC_EXTRACTOR_JAR=/opt/kythe/extractors/javac_extractor.jar
export KYTHE_ROOT_DIRECTORY="$PWD"
export KYTHE_OUTPUT_DIRECTORY="/tmp/kythe"
export KYTHE_CORPUS=otherproject
mkdir -p "$KYTHE_OUTPUT_DIRECTORY"

mvn clean compile \
  -Dmaven.compiler.forceJavacCompilerUse=true \
  -Dmaven.compiler.fork=true \
  -Dmaven.compiler.executable=/opt/kythe/extractors/javac-wrapper.sh

cd ..

java -Xbootclasspath/p:/opt/kythe/indexers/java_indexer.jar com.google.devtools.kythe.analyzers.java.JavaIndexer /tmp/kythe/#3ff8f033c31a2273ebfbbccc40b02b9187b7c87f3f2a690f7bf5821d6451319e.kindex | /opt/kythe/tools/dedup_stream | /opt/kythe/tools/triples >> /tmp/kythe/triples_results.txt
```

Which should result in:
```
2018/08/11 18:01:02 dedup_stream: skipped 8 records
2018/08/11 18:01:02 Skipped 0 reverse edges
2018/08/11 18:01:02 Wrote 529 triples
```

But while trying to reproduce the issue outside of my application I'm running into another issue. The above actually creates an empty `triples_results.txt` file. Not sure what's happening here as the resulting **.kindex** file is only 232 bytes as compared to 6.6kB when I run it in my application.

Considering this isn't the issue I brought up I'll step over this for now and use the **.kindex** that my application produces using: https://github.com/CodeBrig/GitDetective/blob/ccb25e69875a74bfd1a61a602aecf1c33c8086d0/indexer/src/main/groovy/io/gitdetective/indexer/support/KytheMavenBuilder.groovy#L59. I believe this is the correct **.kindex** file anyway.

Now that the **.kindex** has been built and the `triples_results.txt` has been created you can search for: **5d3c119e684b5d35f9c2ccd0145b2dfc18ee25c83bafc92e212af6203459f0e1**.

You won't find any **/kythe/edge/param** facts associated to that signature. This would seem to indicate that the function has no arguments but you can see it does here: https://github.com/BFergerson/otherproject/blob/b0be5053300ef5baabe7706f1cb440e38aa55565/src/main/java/com/gitdetective/App2.java#L26

So now I have two questions:
 - Why does the above script produce empty `triples_results.txt`?
 - Shouldn't there be **/kythe/edge/param** for **5d3c119e684b5d35f9c2ccd0145b2dfc18ee25c83bafc92e212af6203459f0e1** in the resulting `triples_results.txt` file?

**Comment by schroederc** [comment] 2018-08-27 21:21
First of all.  I'm very sorry for taking so long to get back to you.  We've had some technical difficulties as of late...

---

For the first issue, this appears in `/tmp/javac-extractor.err`:

```
SEVERE: compiler error: Source option 1.5 is no longer supported. Use 1.6 or later.
Errors encountered during compilation
```

Your KytheMavenBuilder handles this by adding `-Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8` to the build: https://github.com/CodeBrig/GitDetective/blob/ccb25e69875a74bfd1a61a602aecf1c33c8086d0/indexer/src/main/groovy/io/gitdetective/indexer/support/KytheMavenBuilder.groovy#L76.  You can do the same for the raw invocation and the `.kindex` file will be correctly extracted.

----

For the second case, `param` edges will only be emitted when visiting the function's definition.  Since `App2.java` only references `myMethod2`, only the `function` node will be emitted for the `/kythe/edge/ref` edge.

---

I believe all of this is working as intended so I'm going to close this issue.  Please reopen if you disagree or find another issue.

**Closed by schroederc** 2018-08-27 21:21 UTC
Labels: indexing, java
